### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by dicook** [Abhi-1U/texor#33]
Only listing the problems that appear in the conversions, in the hope that some are easy fixes

- 2019-2/2018-153: 
    - conversion made successfully
    - first example code has  \citetalias{} which didn't get converted to @REF
    - fig 1: timelineExample didn't populate correctly. It is a tikz image, and the changed .tex has an \includegraphics{tiki/figTimelineExample.png} as well as the tikz. I see that the figure is actually in tikz/tikz/figTimelineExample.png so maybe there is an extra tikz added somewhere in the code
    - equation MidPeriodTVM_odd doesn't render correctly
    - code blocks seem to be getting extra` "\"` before braces `"\{"`, `"\}"` 

- 2022-1/2020-36:
    - conversion made successfully
    - this didn't have the "version1" directory appear like the previous paper
    - algorithm 1 doesn't render, but tries to be figure 1, and algorithm 2 text is listed as algorithm 1, figure 2, and algorithm 3 renders as algorithm 1 and figure 3
    - original figure 1, 2 don't render, but interestingly figure 3 does
    -  citation bibtex block doesn't show, maybe because this info is missing from this example paper

**Comment by Abhi-1U** [comment]
I have taken the algorithm problem into consideration  today : 
1. The Lua filter used for numbering figures has been tweaked slightly to find the algorithm images by the `alg/` in the path of the image. [Check Source here](https://github.com/Abhi-1U/texor/commit/3a6773db5774d454594543bc6f3ec3b62bef1ac2#diff-81d8f47e6b690328886278c372aceefdd865189f1d28bcd8a0f2350ae9ec1b53)
2. Since pandoc does not understand the algorithm environment, captions and labels were not included. Hence I have used the stream editor to rename `\begin{algorithm}` to `\begin{figure}`. This will allow for captions and labels to be added to the figure natively. However, one drawback is that this makes the function applicable only one time, if we try to repeat the conversion on the existing directory it will fail as it has already renamed and modified the environment. [Check Source here](https://github.com/Abhi-1U/texor/commit/3a6773db5774d454594543bc6f3ec3b62bef1ac2#diff-14454e0f6247022fd12101afe9f48773b47c683065ff343bec2ea4f0bc5d6cb7)
3. I have also added a bit of pre-processing to remove the caption from the algorithm image. [Check Source here](https://github.com/Abhi-1U/texor/commit/4c6f5eaf44aae85d908316056cf5a4eaede2ee7e)

**Comment by Abhi-1U** [comment]
for the odd sizes of the image, I think pandoc got confused due to some change in `\textwidth` where it would try to convert 
`\includegraphics[width=0.58\textwidth]{barQCA.pdf}` to `\includegraphics[width=0.58\smallskip]{barQCA.pdf}`
Hence the image would have a parameter of width as: `width: 0.58\smallskip` which made no sense. Hence I have modified the Lua filter to read the decimal by using the regex `%d+.%d+` and converting it to a percentage. 

I think the copy function is not robust and sometimes fails to copy images/files over. So I might look into it in some time.

**Comment by Abhi-1U** [comment]
I have found a very ingenious method to find and copy (or convert) image files. 
Instead of trying to search the current working directory for image files or reading the LaTeX file in R and trying to parse for image paths. 
I use pandoc_convert to convert the RJwrapper to a dummy temp file where my Lua filters will read the image paths and write it to an external file, which is then used as a basis for copying image files or converting them to PDF files.

**Comment by Abhi-1U** [comment]
Hopefully most of these and other errors must be fixed by now
