### ISSUE TITLE
JG: Default alt text for figures

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#64]
Comment by @ajrgodfrey - I raised this on the knitr repo first (https://github.com/yihui/knitr/issues/2287) but the consensus was that this should be handled by The R Journal

> Figures generated by R markdown chunks that have a fig.cap but no fig.alt have the same text used for both the alt text and the caption, meaning that people using screen readers hear the same information multiple times (number of graphics in the figure plus one if they navigate through each figure once then look at the caption).
> 
> Example: Figure 1 in https://journal.r-project.org/articles/RJ-2023-001/.
> 
> It would be great if the default value for fig.alt could be changed to "graphic without alt text" so that screen reader users hear this brief message for each graphic in the figure before reading the caption.

In the discussion on the knitr repo, Yihui mentioned a couple of ways to set the default, which may be useful in fixing this:

```r
options(knitr.chunk.fig.alt = "graphic without alt text") # applies to all documents
knitr::opts_chunk$set(fig.alt = "graphic without alt text") # applies to current document
```

**Comment by Abhi-1U** [comment]
From the conversations, I can interpret that,
1. Figures with captions can continue to keep the alt text as captions.
2. Figures without any caption or generic "image" as alt-text can be changed to "graphic without alt-text"
3. My filter would only apply to the legacy articles as they fall into this criteria, rather than having to update the R journal template outright. 
is this right ?

**Comment by ajrgodfrey** [comment]
better to say:

  1.  Figures with captions can continue to keep the alt text as captions.[AJRG]  This is an option, but I believe it should be consistent with the other decisions being made so that there is internal consistency across legacy articles.
  2.  Figures without any caption or generic "image" as alt-text can be changed to "graphic without alt-text"[AJRG]  yes please; we must have something.
  3.  My filter would only apply to the legacy articles as they fall into this criteria, rather than having to update the R journal template outright.[AJRG]  I think we are learning what might be improved about the template, but we are focused on the legacy material in this discussion. The journal should be looking for authors to include proper alt text using fig.alt of their choosing. That might need some more pointers in the template or other journal documentation.

**Comment by hturner** [comment]
For 1, I think our preference would be to have "graphic without alt-text" in this case also (potentially to be replaced with better alt text in a future project). But if this is too much work, keeping the caption as alt text would be acceptable (and certainly better than no alt text).

**Comment by Abhi-1U** [comment]
As an  improvement to the alt-text, I can add a prefix like "Image number:" to  "graphic without alt-text". This might alert the users that there is an image incoming and they can skip the alt-text part if they feel it is repetitive.

**Comment by ajrgodfrey** [comment]
This is a nice idea, but I wonder if it invites headaches for checking how well it works, especially in conjunction with other graphics that might be imported using other approaches.
Neat if it could be done elegantly "graphic x has no alt text" and is guaranteed to have internal consistency within a document = no unnumbered graphics if any are numbered.

Most screen reader users will know how many graphics are on an HTML page as soon as we open it. Anyone reading the legacy material will "know" to expect graphics without alt text. We're just showing them where the graphics are, not what they contain.

**Comment by hturner** [comment]
Regarding point 3 in your earlier comment (https://github.com/Abhi-1U/texor/issues/64#issuecomment-1712507234), once we have settled on a way forward for legacy articles, we might propose a change to the default alt text used by rjtools for new articles. Ideally, new articles should have proper alt text, but it would be good to have consistent defaults.

**Comment by ajrgodfrey** [comment]
Yes. Sensible (albeit undesirable) defaults along with helpful guidance is the pragmatic way forwards. Idealism is (currently) far from realism; that gap may close in time.

**Comment by Abhi-1U** [comment]
As there are overheads in checking for the alt-text with numbering and it may be inconsistent, I will avoid numbering the alt-text.
As a general default rule, all Images would have the "graphics without alt text" default alt text, unless they are updated in future as it is being planned.
This would apply to all legacy articles.
