### ISSUE TITLE
R Vignette needs a makeover and should include more details

### ISSUE THREAD

**Issue by Abhi-1U** [Abhi-1U/texor#8]
### The enhancement 

The vignette with this package needs a fresh coat of paint and more detailed guides.

**Comment by Abhi-1U** [comment]
upcoming updates to the package will be documented and contain a lot of man pages, vignettes, inline documentation, guides, examples and tutorials.

A list of upcoming vignettes in pipeline :

- [ ]  bibliography.Rmd
- [ ]  change-log.Rmd
- [ ]  code-env.Rmd
- [ ]  conversion-instructions.Rmd
- [ ]  dependencies.Rmd
- [ ]  image.Rmd
- [ ]  install-texor.Rmd
- [ ]  math.Rmd
- [ ]  table.Rmd
- [ ]  tikz.Rmd

**Comment by hturner** [comment]
Rather than put the Change Log in a vignette, it would be better to use a NEWS.md file (https://r-pkgs.org/other-markdown.html#news).

If you are planning a large number of vignettes, it may be helpful to number them (e.g. https://cran.r-project.org/web/packages/dataverse/) or at least make it clear which is the main vignette. The main vignette will typically be called something like "Overview of texor" or "Introduction to texor" and give a start to finish example workflow, with brief descriptions of the main functions. This gets people up and running quickly, they can then look at the other vignettes for more specifics. This will probably replace the old "my-vignette.Rmd".

Instructions on how to install texor would typically go in README.md of this repo. This should also have a very basic example - e.g. converting a single .tex file with a one-line command.

**Comment by Abhi-1U** [comment]
I have merged the vignettes to make it simpler and more informative.
